### ISSUE TITLE
用法有吗？

### ISSUE THREAD

**Issue by xiaohuoni** [DiamondYuan/dva-helper#9]
我装了插件，没什么反应

**Comment by DiamondYuan** [comment]
输入 type: 然后就有所以 action 的提示了。

**Comment by DiamondYuan** [comment]
目前只会加载 src/modules 里面的文件。在完善中。

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/56948156-e20ccc00-6b61-11e9-8174-5ad7d64a3fb6.png)

**Comment by DiamondYuan** [comment]
目前的触发字符是冒号，条件是当前行有 type 这个字符。

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/56948392-91e23980-6b62-11e9-95a8-918f73298025.png)



刚才试了一下 antd pro

**Comment by xiaohuoni** [comment]
就是我这样子啊，什么也没有

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/56948477-d2da4e00-6b62-11e9-8d99-2431cdaf6f01.png)





目前读取 model 的方法很简单。可能没读取到。还在开发中。

**Comment by DiamondYuan** [comment]
不好意思，现在版本还没有日志，我下一个版本就把日志加上，这样也好调试。

**Comment by xiaohuoni** [comment]
pro项目可以。其他项目不行，就算使用pro改的项目，也不行。没事先不管吧

**Comment by DiamondYuan** [comment]
参考了 umi 的源码，现在能正确的读取 global models 和 page models 了。
解析文件的时候也加了 try cache。

**Comment by DiamondYuan** [comment]
@xiaohuoni  _可以试一下最新的 0.1.0 版

**Comment by xiaohuoni** [comment]
好

**Comment by loneyclown** [comment]
我的还是无效，感觉就好像是整个插件都无效，什么功能都无法使用，是配置的问题嘛。我路由配置在`.umirc.js`文件，我配置`umi_pro.router_config_path`的时候，不知道要写什么样的路径，相对路径和绝对路径都试过了。还是没有什么反应。

**Comment by xiaohuoni** [comment]
我的也是无效，没有作用，不知道为啥，应该不需要配置才对的
